package com.android.systemui.statusbar.phone;

import android.app.ActivityManager;
import android.content.ContentResolver;
import android.content.res.Resources;
import android.os.Handler;
import android.os.PowerManager;
import android.os.UserManager;
import android.view.LayoutInflater;
import android.view.accessibility.AccessibilityManager;
import com.android.internal.jank.InteractionJankMonitor;
import com.android.internal.logging.MetricsLogger;
import com.android.internal.util.LatencyTracker;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.LockIconViewController;
import com.android.keyguard.dagger.KeyguardQsUserSwitchComponent;
import com.android.keyguard.dagger.KeyguardStatusBarViewComponent;
import com.android.keyguard.dagger.KeyguardStatusViewComponent;
import com.android.keyguard.dagger.KeyguardUserSwitcherComponent;
import com.android.p012wm.shell.animation.FlingAnimationUtils;
import com.android.systemui.biometrics.AuthController;
import com.android.systemui.classifier.FalsingCollector;
import com.android.systemui.communal.CommunalSourceMonitor;
import com.android.systemui.communal.CommunalStateController;
import com.android.systemui.communal.dagger.CommunalViewComponent;
import com.android.systemui.controls.dagger.ControlsComponent;
import com.android.systemui.doze.DozeLog;
import com.android.systemui.flags.FeatureFlags;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.keyguard.KeyguardUnlockAnimationController;
import com.android.systemui.media.KeyguardMediaController;
import com.android.systemui.media.MediaDataManager;
import com.android.systemui.media.MediaHierarchyManager;
import com.android.systemui.model.SysUiState;
import com.android.systemui.navigationbar.NavigationModeController;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.plugins.statusbar.StatusBarStateController;
import com.android.systemui.qrcodescanner.controller.QRCodeScannerController;
import com.android.systemui.screenrecord.RecordingController;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.LockscreenShadeTransitionController;
import com.android.systemui.statusbar.NotificationLockscreenUserManager;
import com.android.systemui.statusbar.NotificationRemoteInputManager;
import com.android.systemui.statusbar.NotificationShadeDepthController;
import com.android.systemui.statusbar.NotificationShadeWindowController;
import com.android.systemui.statusbar.PulseExpansionHandler;
import com.android.systemui.statusbar.QsFrameTranslateController;
import com.android.systemui.statusbar.VibratorHelper;
import com.android.systemui.statusbar.events.PrivacyDotViewController;
import com.android.systemui.statusbar.notification.ConversationNotificationManager;
import com.android.systemui.statusbar.notification.DynamicPrivacyController;
import com.android.systemui.statusbar.notification.NotificationEntryManager;
import com.android.systemui.statusbar.notification.NotificationWakeUpCoordinator;
import com.android.systemui.statusbar.notification.collection.legacy.NotificationGroupManagerLegacy;
import com.android.systemui.statusbar.notification.stack.AmbientState;
import com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController;
import com.android.systemui.statusbar.phone.panelstate.PanelExpansionStateManager;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.window.StatusBarWindowStateController;
import com.android.systemui.unfold.SysUIUnfoldComponent;
import com.android.systemui.util.settings.SecureSettings;
import com.android.systemui.wallet.controller.QuickAccessWalletController;
import dagger.internal.Factory;
import java.util.Optional;
import java.util.concurrent.Executor;
import javax.inject.Provider;

public final class NotificationPanelViewController_Factory implements Factory<NotificationPanelViewController> {
    public final Provider<AccessibilityManager> accessibilityManagerProvider;
    public final Provider<ActivityManager> activityManagerProvider;
    public final Provider<AmbientState> ambientStateProvider;
    public final Provider<AuthController> authControllerProvider;
    public final Provider<KeyguardBypassController> bypassControllerProvider;
    public final Provider<CommandQueue> commandQueueProvider;
    public final Provider<CommunalSourceMonitor> communalSourceMonitorProvider;
    public final Provider<CommunalStateController> communalStateControllerProvider;
    public final Provider<CommunalViewComponent.Factory> communalViewComponentFactoryProvider;
    public final Provider<ConfigurationController> configurationControllerProvider;
    public final Provider<ContentResolver> contentResolverProvider;
    public final Provider<ControlsComponent> controlsComponentProvider;
    public final Provider<ConversationNotificationManager> conversationNotificationManagerProvider;
    public final Provider<NotificationWakeUpCoordinator> coordinatorProvider;
    public final Provider<Integer> displayIdProvider;
    public final Provider<DozeLog> dozeLogProvider;
    public final Provider<DozeParameters> dozeParametersProvider;
    public final Provider<DynamicPrivacyController> dynamicPrivacyControllerProvider;
    public final Provider<FalsingCollector> falsingCollectorProvider;
    public final Provider<FalsingManager> falsingManagerProvider;
    public final Provider<FeatureFlags> featureFlagsProvider;
    public final Provider<FlingAnimationUtils.Builder> flingAnimationUtilsBuilderProvider;
    public final Provider<FragmentService> fragmentServiceProvider;
    public final Provider<NotificationGroupManagerLegacy> groupManagerProvider;
    public final Provider<Handler> handlerProvider;
    public final Provider<InteractionJankMonitor> interactionJankMonitorProvider;
    public final Provider<KeyguardMediaController> keyguardMediaControllerProvider;
    public final Provider<KeyguardQsUserSwitchComponent.Factory> keyguardQsUserSwitchComponentFactoryProvider;
    public final Provider<KeyguardStateController> keyguardStateControllerProvider;
    public final Provider<KeyguardStatusBarViewComponent.Factory> keyguardStatusBarViewComponentFactoryProvider;
    public final Provider<KeyguardStatusViewComponent.Factory> keyguardStatusViewComponentFactoryProvider;
    public final Provider<KeyguardUnlockAnimationController> keyguardUnlockAnimationControllerProvider;
    public final Provider<KeyguardUpdateMonitor> keyguardUpdateMonitorProvider;
    public final Provider<KeyguardUserSwitcherComponent.Factory> keyguardUserSwitcherComponentFactoryProvider;
    public final Provider<LatencyTracker> latencyTrackerProvider;
    public final Provider<LayoutInflater> layoutInflaterProvider;
    public final Provider<LockIconViewController> lockIconViewControllerProvider;
    public final Provider<LockscreenGestureLogger> lockscreenGestureLoggerProvider;
    public final Provider<LockscreenShadeTransitionController> lockscreenShadeTransitionControllerProvider;
    public final Provider<MediaDataManager> mediaDataManagerProvider;
    public final Provider<MediaHierarchyManager> mediaHierarchyManagerProvider;
    public final Provider<MetricsLogger> metricsLoggerProvider;
    public final Provider<NavigationModeController> navigationModeControllerProvider;
    public final Provider<NotificationEntryManager> notificationEntryManagerProvider;
    public final Provider<NotificationIconAreaController> notificationIconAreaControllerProvider;
    public final Provider<NotificationLockscreenUserManager> notificationLockscreenUserManagerProvider;
    public final Provider<NotificationShadeDepthController> notificationShadeDepthControllerProvider;
    public final Provider<NotificationShadeWindowController> notificationShadeWindowControllerProvider;
    public final Provider<NotificationStackScrollLayoutController> notificationStackScrollLayoutControllerProvider;
    public final Provider<NotificationsQSContainerController> notificationsQSContainerControllerProvider;
    public final Provider<PanelExpansionStateManager> panelExpansionStateManagerProvider;
    public final Provider<PowerManager> powerManagerProvider;
    public final Provider<PrivacyDotViewController> privacyDotViewControllerProvider;
    public final Provider<PulseExpansionHandler> pulseExpansionHandlerProvider;
    public final Provider<QRCodeScannerController> qrCodeScannerControllerProvider;
    public final Provider<QsFrameTranslateController> qsFrameTranslateControllerProvider;
    public final Provider<QuickAccessWalletController> quickAccessWalletControllerProvider;
    public final Provider<RecordingController> recordingControllerProvider;
    public final Provider<NotificationRemoteInputManager> remoteInputManagerProvider;
    public final Provider<Resources> resourcesProvider;
    public final Provider<ScreenOffAnimationController> screenOffAnimationControllerProvider;
    public final Provider<ScrimController> scrimControllerProvider;
    public final Provider<SecureSettings> secureSettingsProvider;
    public final Provider<SplitShadeHeaderController> splitShadeHeaderControllerProvider;
    public final Provider<StatusBarKeyguardViewManager> statusBarKeyguardViewManagerProvider;
    public final Provider<StatusBarStateController> statusBarStateControllerProvider;
    public final Provider<StatusBarTouchableRegionManager> statusBarTouchableRegionManagerProvider;
    public final Provider<StatusBarWindowStateController> statusBarWindowStateControllerProvider;
    public final Provider<SysUiState> sysUiStateProvider;
    public final Provider<TapAgainViewController> tapAgainViewControllerProvider;
    public final Provider<Executor> uiExecutorProvider;
    public final Provider<Optional<SysUIUnfoldComponent>> unfoldComponentProvider;
    public final Provider<UserManager> userManagerProvider;
    public final Provider<VibratorHelper> vibratorHelperProvider;
    public final Provider<NotificationPanelView> viewProvider;

    public NotificationPanelViewController_Factory(Provider<NotificationPanelView> provider, Provider<Resources> provider2, Provider<Handler> provider3, Provider<LayoutInflater> provider4, Provider<FeatureFlags> provider5, Provider<NotificationWakeUpCoordinator> provider6, Provider<PulseExpansionHandler> provider7, Provider<DynamicPrivacyController> provider8, Provider<KeyguardBypassController> provider9, Provider<FalsingManager> provider10, Provider<FalsingCollector> provider11, Provider<NotificationLockscreenUserManager> provider12, Provider<NotificationEntryManager> provider13, Provider<CommunalStateController> provider14, Provider<KeyguardStateController> provider15, Provider<StatusBarStateController> provider16, Provider<StatusBarWindowStateController> provider17, Provider<NotificationShadeWindowController> provider18, Provider<DozeLog> provider19, Provider<DozeParameters> provider20, Provider<CommandQueue> provider21, Provider<VibratorHelper> provider22, Provider<LatencyTracker> provider23, Provider<PowerManager> provider24, Provider<AccessibilityManager> provider25, Provider<Integer> provider26, Provider<KeyguardUpdateMonitor> provider27, Provider<CommunalSourceMonitor> provider28, Provider<MetricsLogger> provider29, Provider<ActivityManager> provider30, Provider<ConfigurationController> provider31, Provider<FlingAnimationUtils.Builder> provider32, Provider<StatusBarTouchableRegionManager> provider33, Provider<ConversationNotificationManager> provider34, Provider<MediaHierarchyManager> provider35, Provider<StatusBarKeyguardViewManager> provider36, Provider<NotificationsQSContainerController> provider37, Provider<NotificationStackScrollLayoutController> provider38, Provider<KeyguardStatusViewComponent.Factory> provider39, Provider<KeyguardQsUserSwitchComponent.Factory> provider40, Provider<KeyguardUserSwitcherComponent.Factory> provider41, Provider<KeyguardStatusBarViewComponent.Factory> provider42, Provider<CommunalViewComponent.Factory> provider43, Provider<LockscreenShadeTransitionController> provider44, Provider<NotificationGroupManagerLegacy> provider45, Provider<NotificationIconAreaController> provider46, Provider<AuthController> provider47, Provider<ScrimController> provider48, Provider<UserManager> provider49, Provider<MediaDataManager> provider50, Provider<NotificationShadeDepthController> provider51, Provider<AmbientState> provider52, Provider<LockIconViewController> provider53, Provider<KeyguardMediaController> provider54, Provider<PrivacyDotViewController> provider55, Provider<TapAgainViewController> provider56, Provider<NavigationModeController> provider57, Provider<FragmentService> provider58, Provider<ContentResolver> provider59, Provider<QuickAccessWalletController> provider60, Provider<QRCodeScannerController> provider61, Provider<RecordingController> provider62, Provider<Executor> provider63, Provider<SecureSettings> provider64, Provider<SplitShadeHeaderController> provider65, Provider<ScreenOffAnimationController> provider66, Provider<LockscreenGestureLogger> provider67, Provider<PanelExpansionStateManager> provider68, Provider<NotificationRemoteInputManager> provider69, Provider<Optional<SysUIUnfoldComponent>> provider70, Provider<ControlsComponent> provider71, Provider<InteractionJankMonitor> provider72, Provider<QsFrameTranslateController> provider73, Provider<SysUiState> provider74, Provider<KeyguardUnlockAnimationController> provider75) {
        this.viewProvider = provider;
        this.resourcesProvider = provider2;
        this.handlerProvider = provider3;
        this.layoutInflaterProvider = provider4;
        this.featureFlagsProvider = provider5;
        this.coordinatorProvider = provider6;
        this.pulseExpansionHandlerProvider = provider7;
        this.dynamicPrivacyControllerProvider = provider8;
        this.bypassControllerProvider = provider9;
        this.falsingManagerProvider = provider10;
        this.falsingCollectorProvider = provider11;
        this.notificationLockscreenUserManagerProvider = provider12;
        this.notificationEntryManagerProvider = provider13;
        this.communalStateControllerProvider = provider14;
        this.keyguardStateControllerProvider = provider15;
        this.statusBarStateControllerProvider = provider16;
        this.statusBarWindowStateControllerProvider = provider17;
        this.notificationShadeWindowControllerProvider = provider18;
        this.dozeLogProvider = provider19;
        this.dozeParametersProvider = provider20;
        this.commandQueueProvider = provider21;
        this.vibratorHelperProvider = provider22;
        this.latencyTrackerProvider = provider23;
        this.powerManagerProvider = provider24;
        this.accessibilityManagerProvider = provider25;
        this.displayIdProvider = provider26;
        this.keyguardUpdateMonitorProvider = provider27;
        this.communalSourceMonitorProvider = provider28;
        this.metricsLoggerProvider = provider29;
        this.activityManagerProvider = provider30;
        this.configurationControllerProvider = provider31;
        this.flingAnimationUtilsBuilderProvider = provider32;
        this.statusBarTouchableRegionManagerProvider = provider33;
        this.conversationNotificationManagerProvider = provider34;
        this.mediaHierarchyManagerProvider = provider35;
        this.statusBarKeyguardViewManagerProvider = provider36;
        this.notificationsQSContainerControllerProvider = provider37;
        this.notificationStackScrollLayoutControllerProvider = provider38;
        this.keyguardStatusViewComponentFactoryProvider = provider39;
        this.keyguardQsUserSwitchComponentFactoryProvider = provider40;
        this.keyguardUserSwitcherComponentFactoryProvider = provider41;
        this.keyguardStatusBarViewComponentFactoryProvider = provider42;
        this.communalViewComponentFactoryProvider = provider43;
        this.lockscreenShadeTransitionControllerProvider = provider44;
        this.groupManagerProvider = provider45;
        this.notificationIconAreaControllerProvider = provider46;
        this.authControllerProvider = provider47;
        this.scrimControllerProvider = provider48;
        this.userManagerProvider = provider49;
        this.mediaDataManagerProvider = provider50;
        this.notificationShadeDepthControllerProvider = provider51;
        this.ambientStateProvider = provider52;
        this.lockIconViewControllerProvider = provider53;
        this.keyguardMediaControllerProvider = provider54;
        this.privacyDotViewControllerProvider = provider55;
        this.tapAgainViewControllerProvider = provider56;
        this.navigationModeControllerProvider = provider57;
        this.fragmentServiceProvider = provider58;
        this.contentResolverProvider = provider59;
        this.quickAccessWalletControllerProvider = provider60;
        this.qrCodeScannerControllerProvider = provider61;
        this.recordingControllerProvider = provider62;
        this.uiExecutorProvider = provider63;
        this.secureSettingsProvider = provider64;
        this.splitShadeHeaderControllerProvider = provider65;
        this.screenOffAnimationControllerProvider = provider66;
        this.lockscreenGestureLoggerProvider = provider67;
        this.panelExpansionStateManagerProvider = provider68;
        this.remoteInputManagerProvider = provider69;
        this.unfoldComponentProvider = provider70;
        this.controlsComponentProvider = provider71;
        this.interactionJankMonitorProvider = provider72;
        this.qsFrameTranslateControllerProvider = provider73;
        this.sysUiStateProvider = provider74;
        this.keyguardUnlockAnimationControllerProvider = provider75;
    }

    public static NotificationPanelViewController_Factory create(Provider<NotificationPanelView> provider, Provider<Resources> provider2, Provider<Handler> provider3, Provider<LayoutInflater> provider4, Provider<FeatureFlags> provider5, Provider<NotificationWakeUpCoordinator> provider6, Provider<PulseExpansionHandler> provider7, Provider<DynamicPrivacyController> provider8, Provider<KeyguardBypassController> provider9, Provider<FalsingManager> provider10, Provider<FalsingCollector> provider11, Provider<NotificationLockscreenUserManager> provider12, Provider<NotificationEntryManager> provider13, Provider<CommunalStateController> provider14, Provider<KeyguardStateController> provider15, Provider<StatusBarStateController> provider16, Provider<StatusBarWindowStateController> provider17, Provider<NotificationShadeWindowController> provider18, Provider<DozeLog> provider19, Provider<DozeParameters> provider20, Provider<CommandQueue> provider21, Provider<VibratorHelper> provider22, Provider<LatencyTracker> provider23, Provider<PowerManager> provider24, Provider<AccessibilityManager> provider25, Provider<Integer> provider26, Provider<KeyguardUpdateMonitor> provider27, Provider<CommunalSourceMonitor> provider28, Provider<MetricsLogger> provider29, Provider<ActivityManager> provider30, Provider<ConfigurationController> provider31, Provider<FlingAnimationUtils.Builder> provider32, Provider<StatusBarTouchableRegionManager> provider33, Provider<ConversationNotificationManager> provider34, Provider<MediaHierarchyManager> provider35, Provider<StatusBarKeyguardViewManager> provider36, Provider<NotificationsQSContainerController> provider37, Provider<NotificationStackScrollLayoutController> provider38, Provider<KeyguardStatusViewComponent.Factory> provider39, Provider<KeyguardQsUserSwitchComponent.Factory> provider40, Provider<KeyguardUserSwitcherComponent.Factory> provider41, Provider<KeyguardStatusBarViewComponent.Factory> provider42, Provider<CommunalViewComponent.Factory> provider43, Provider<LockscreenShadeTransitionController> provider44, Provider<NotificationGroupManagerLegacy> provider45, Provider<NotificationIconAreaController> provider46, Provider<AuthController> provider47, Provider<ScrimController> provider48, Provider<UserManager> provider49, Provider<MediaDataManager> provider50, Provider<NotificationShadeDepthController> provider51, Provider<AmbientState> provider52, Provider<LockIconViewController> provider53, Provider<KeyguardMediaController> provider54, Provider<PrivacyDotViewController> provider55, Provider<TapAgainViewController> provider56, Provider<NavigationModeController> provider57, Provider<FragmentService> provider58, Provider<ContentResolver> provider59, Provider<QuickAccessWalletController> provider60, Provider<QRCodeScannerController> provider61, Provider<RecordingController> provider62, Provider<Executor> provider63, Provider<SecureSettings> provider64, Provider<SplitShadeHeaderController> provider65, Provider<ScreenOffAnimationController> provider66, Provider<LockscreenGestureLogger> provider67, Provider<PanelExpansionStateManager> provider68, Provider<NotificationRemoteInputManager> provider69, Provider<Optional<SysUIUnfoldComponent>> provider70, Provider<ControlsComponent> provider71, Provider<InteractionJankMonitor> provider72, Provider<QsFrameTranslateController> provider73, Provider<SysUiState> provider74, Provider<KeyguardUnlockAnimationController> provider75) {
        return new NotificationPanelViewController_Factory(provider, provider2, provider3, provider4, provider5, provider6, provider7, provider8, provider9, provider10, provider11, provider12, provider13, provider14, provider15, provider16, provider17, provider18, provider19, provider20, provider21, provider22, provider23, provider24, provider25, provider26, provider27, provider28, provider29, provider30, provider31, provider32, provider33, provider34, provider35, provider36, provider37, provider38, provider39, provider40, provider41, provider42, provider43, provider44, provider45, provider46, provider47, provider48, provider49, provider50, provider51, provider52, provider53, provider54, provider55, provider56, provider57, provider58, provider59, provider60, provider61, provider62, provider63, provider64, provider65, provider66, provider67, provider68, provider69, provider70, provider71, provider72, provider73, provider74, provider75);
    }

    public final Object get() {
        return new NotificationPanelViewController(this.viewProvider.get(), this.resourcesProvider.get(), this.handlerProvider.get(), this.layoutInflaterProvider.get(), this.featureFlagsProvider.get(), this.coordinatorProvider.get(), this.pulseExpansionHandlerProvider.get(), this.dynamicPrivacyControllerProvider.get(), this.bypassControllerProvider.get(), this.falsingManagerProvider.get(), this.falsingCollectorProvider.get(), this.notificationLockscreenUserManagerProvider.get(), this.notificationEntryManagerProvider.get(), this.communalStateControllerProvider.get(), this.keyguardStateControllerProvider.get(), this.statusBarStateControllerProvider.get(), this.statusBarWindowStateControllerProvider.get(), this.notificationShadeWindowControllerProvider.get(), this.dozeLogProvider.get(), this.dozeParametersProvider.get(), this.commandQueueProvider.get(), this.vibratorHelperProvider.get(), this.latencyTrackerProvider.get(), this.powerManagerProvider.get(), this.accessibilityManagerProvider.get(), this.displayIdProvider.get().intValue(), this.keyguardUpdateMonitorProvider.get(), this.communalSourceMonitorProvider.get(), this.metricsLoggerProvider.get(), this.activityManagerProvider.get(), this.configurationControllerProvider.get(), this.flingAnimationUtilsBuilderProvider, this.statusBarTouchableRegionManagerProvider.get(), this.conversationNotificationManagerProvider.get(), this.mediaHierarchyManagerProvider.get(), this.statusBarKeyguardViewManagerProvider.get(), this.notificationsQSContainerControllerProvider.get(), this.notificationStackScrollLayoutControllerProvider.get(), this.keyguardStatusViewComponentFactoryProvider.get(), this.keyguardQsUserSwitchComponentFactoryProvider.get(), this.keyguardUserSwitcherComponentFactoryProvider.get(), this.keyguardStatusBarViewComponentFactoryProvider.get(), this.communalViewComponentFactoryProvider.get(), this.lockscreenShadeTransitionControllerProvider.get(), this.groupManagerProvider.get(), this.notificationIconAreaControllerProvider.get(), this.authControllerProvider.get(), this.scrimControllerProvider.get(), this.userManagerProvider.get(), this.mediaDataManagerProvider.get(), this.notificationShadeDepthControllerProvider.get(), this.ambientStateProvider.get(), this.lockIconViewControllerProvider.get(), this.keyguardMediaControllerProvider.get(), this.privacyDotViewControllerProvider.get(), this.tapAgainViewControllerProvider.get(), this.navigationModeControllerProvider.get(), this.fragmentServiceProvider.get(), this.contentResolverProvider.get(), this.quickAccessWalletControllerProvider.get(), this.qrCodeScannerControllerProvider.get(), this.recordingControllerProvider.get(), this.uiExecutorProvider.get(), this.secureSettingsProvider.get(), this.splitShadeHeaderControllerProvider.get(), this.screenOffAnimationControllerProvider.get(), this.lockscreenGestureLoggerProvider.get(), this.panelExpansionStateManagerProvider.get(), this.remoteInputManagerProvider.get(), this.unfoldComponentProvider.get(), this.controlsComponentProvider.get(), this.interactionJankMonitorProvider.get(), this.qsFrameTranslateControllerProvider.get(), this.sysUiStateProvider.get(), this.keyguardUnlockAnimationControllerProvider.get());
    }
}
